[[command]]
name = "rbenv"
url = "https://github.com/rbenv/rbenv#readme"
bare_flags = ["--help", "--version", "-V", "-h"]

[[command.sub]]
name = "help"
standalone = ["--help", "-h"]

[[command.sub]]
name = "root"
standalone = ["--help", "-h"]

[[command.sub]]
name = "shims"
standalone = ["--help", "-h"]

[[command.sub]]
name = "version"
standalone = ["--help", "-h"]

[[command.sub]]
name = "versions"
standalone = ["--help", "-h"]

[[command.sub]]
name = "which"
standalone = ["--help", "-h"]
