[[command]]
name = "composer"
url = "https://getcomposer.org/doc/03-cli.md"
bare_flags = ["--help", "--version", "-V", "-h"]

[[command.sub]]
name = "about"
standalone = ["--help", "-h"]

[[command.sub]]
name = "audit"
standalone = ["--abandoned", "--help", "--locked", "--no-dev", "-h"]
valued = ["--format", "-f"]

[[command.sub]]
name = "check-platform-reqs"
standalone = ["--help", "-h"]

[[command.sub]]
name = "diagnose"
standalone = ["--help", "-h"]

[[command.sub]]
name = "fund"
standalone = ["--help", "-h"]

[[command.sub]]
name = "help"
standalone = ["--help", "-h"]

[[command.sub]]
name = "info"
standalone = [
    "--all", "--available", "--direct", "--help", "--installed", "--latest",
    "--locked", "--minor-only", "--name-only", "--no-dev", "--outdated",
    "--path", "--platform", "--self", "--strict", "--tree", "--versions",
    "-D", "-H", "-N", "-P", "-a", "-h", "-i", "-l", "-o", "-s", "-t",
]
valued = ["--format", "--ignore", "-f"]

[[command.sub]]
name = "licenses"
standalone = ["--help", "-h"]

[[command.sub]]
name = "outdated"
standalone = [
    "--all", "--direct", "--help", "--locked", "--minor-only",
    "--no-dev", "--strict",
    "-D", "-a", "-h", "-m",
]
valued = ["--format", "--ignore", "-f"]

[[command.sub]]
name = "show"
standalone = [
    "--all", "--available", "--direct", "--help", "--installed", "--latest",
    "--locked", "--minor-only", "--name-only", "--no-dev", "--outdated",
    "--path", "--platform", "--self", "--strict", "--tree", "--versions",
    "-D", "-H", "-N", "-P", "-a", "-h", "-i", "-l", "-o", "-s", "-t",
]
valued = ["--format", "--ignore", "-f"]

[[command.sub]]
name = "suggests"
standalone = ["--help", "-h"]

[[command]]
name = "craft"
url = "https://craftcms.com/docs/5.x/reference/cli.html"
bare_flags = ["--help", "--version", "-V", "-h"]

[[command.sub]]
name = "env/show"
bare = false
standalone = ["--help", "-h"]

[[command.sub]]
name = "graphql/list-schemas"
standalone = ["--help", "-h"]

[[command.sub]]
name = "graphql/print-schema"
bare = false
standalone = ["--help", "-h"]

[[command.sub]]
name = "help"
standalone = ["--help", "-h"]

[[command.sub]]
name = "install/check"
standalone = ["--help", "-h"]

[[command.sub]]
name = "migrate/history"
standalone = ["--help", "-h"]

[[command.sub]]
name = "migrate/new"
standalone = ["--help", "-h"]

[[command.sub]]
name = "pc/diff"
standalone = ["--help", "-h"]

[[command.sub]]
name = "pc/export"
standalone = ["--help", "-h"]

[[command.sub]]
name = "pc/get"
bare = false
standalone = ["--help", "-h"]

[[command.sub]]
name = "plugin/list"
standalone = ["--help", "-h"]

[[command.sub]]
name = "queue/info"
standalone = ["--help", "-h"]

[[command.sub]]
name = "update/info"
standalone = ["--help", "-h"]

[[command.sub]]
name = "users/list-admins"
standalone = ["--help", "-h"]
