[[command]]
name = "secretlint"
url = "https://github.com/secretlint/secretlint"
level = "SafeRead"
bare = false
standalone = [
    "--help", "--no-color", "--no-maskSecrets",
    "--no-terminalLink", "--profile", "--version",
    "-h",
]
valued = [
    "--format", "--locale",
    "--secretlintignore", "--secretlintrc",
    "--secretlintrcJSON",
]
