[[command]]
name = "@johnnymorganz/stylua-bin"
url = "https://github.com/JohnnyMorganz/StyLua"
level = "Inert"
bare = false
require_any = ["--check", "--verify"]
standalone = [
    "--allow-hidden", "--check", "--color",
    "--help", "--no-editorconfig", "--respect-ignores",
    "--verbose", "--verify", "--version",
    "-V", "-h",
]
valued = [
    "--config-path", "--glob", "--num-threads",
    "--output-format", "--search-parent-directories",
    "-f", "-g",
]
