[[command]]
name = "ag"
url = "https://github.com/ggreer/the_silver_searcher"
level = "Inert"
bare = false
standalone = [
    "--ackmate", "--all-text", "--all-types", "--case-sensitive",
    "--color", "--column", "--count", "--filename",
    "--files-with-matches", "--files-without-matches", "--fixed-strings",
    "--follow", "--group", "--heading", "--help", "--hidden", "--ignore-case",
    "--invert-match", "--line-numbers", "--literal",
    "--no-break", "--no-color", "--no-filename", "--no-follow",
    "--no-group", "--no-heading", "--no-numbers", "--nobreak",
    "--nocolor", "--nofilename", "--nofollow", "--nogroup",
    "--noheading", "--nonumbers", "--null", "--numbers",
    "--one-device", "--only-matching", "--print-all-files",
    "--print-long-lines", "--search-binary", "--search-files",
    "--search-zip", "--silent", "--smart-case", "--stats",
    "--unrestricted", "--version", "--vimgrep", "--word-regexp",
    "-0", "-H", "-L", "-Q", "-S", "-U", "-V",
    "-a", "-c", "-f", "-h", "-i", "-l", "-n", "-s", "-u", "-v", "-w",
]
valued = [
    "--after", "--before", "--context", "--depth",
    "--file-search-regex", "--ignore", "--max-count",
    "--pager", "--path-to-ignore", "--workers",
    "-A", "-B", "-C", "-G", "-g", "-m",
]
