use crate::handlers;

pub struct CommandDoc {
    pub name: &'static str,
    pub kind: DocKind,
    pub description: &'static str,
}

pub enum DocKind {
    AlwaysSafe,
    Handler,
}

pub fn all_command_docs() -> Vec<CommandDoc> {
    let mut docs = safe_cmd_docs();
    docs.extend(handlers::handler_docs());
    docs.sort_by_key(|d| d.name);
    docs
}

pub fn render_markdown(docs: &[CommandDoc]) -> String {
    let mut out = String::from(
        "# Supported Commands\n\
         \n\
         Auto-generated by `safe-chains --list-commands`.\n\
         \n\
         Any command with only `--version` or `--help` as its sole argument is always allowed.\n\
         \n\
         ## Unconditionally Safe\n\
         \n\
         These commands are allowed with any arguments.\n\
         \n\
         | Command | Description |\n\
         |---------|-------------|\n",
    );

    for doc in docs.iter().filter(|d| matches!(d.kind, DocKind::AlwaysSafe)) {
        out.push_str(&format!("| `{}` | {} |\n", doc.name, doc.description));
    }

    out.push_str("\n## Handled Commands\n\nThese commands are allowed with specific subcommands or flags.\n\n");

    for doc in docs.iter().filter(|d| matches!(d.kind, DocKind::Handler)) {
        out.push_str(&format!("### `{}`\n\n{}\n\n", doc.name, doc.description));
    }

    out
}

fn safe_cmd_docs() -> Vec<CommandDoc> {
    handlers::SAFE_CMD_ENTRIES
        .iter()
        .map(|&(name, description)| CommandDoc {
            name,
            kind: DocKind::AlwaysSafe,
            description,
        })
        .collect()
}
